version: "3.8"
services:
  nginx:
    image: nginx
    ports:
    - 2112:2112
    volumes:
    - ./z-docker-compose-configs/nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
    - -nginx.scrape-uri
    - http://nginx:9113/stub_status

  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus-data:/prometheus
    - ./z-docker-compose-configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./z-docker-compose-configs/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    - ./z-docker-compose-configs/grafana/dashboards/:/var/lib/grafana/dashboards/

  aiko:
    image: mahtues/aiko
    build:
      context: .
      target: aiko-release
    deploy:
      replicas: 5

volumes:
  grafana-storage:
  prometheus-data:
