#!/usr/bin/env bash

COOKIE_FILE=/tmp/cookies

# root
curl -i http://localhost/
echo ---

# create account
curl -i -X POST -d 'username=matheus&password=root&email=fake@asd.com' http://localhost/signup
echo ---

# sign in with wrong password
curl -i -c ${COOKIE_FILE} -X POST -d 'username=matheus&password=wrong' http://localhost/signin
echo ---

# sign in
curl -i -c ${COOKIE_FILE} -X POST -d 'username=matheus&password=root' http://localhost/signin
echo ---

# home
curl -i -b ${COOKIE_FILE} -X GET http://localhost/home
echo ---

# sign out
curl -i -b ${COOKIE_FILE} -X GET http://localhost/signout
echo ---

# home
curl -i -b ${COOKIE_FILE} -X GET http://localhost/home
