#!/usr/bin/env bash

COOKIE_FILE=/tmp/cookies
HOST_URL=http://localhost:8080

# root
curl -i $HOST_URL/
echo ---

# create account
curl -i -X POST -d 'username=matheus&password=root&email=fake@asd.com' $HOST_URL/signup
echo ---

# sign in with wrong password
curl -i -c ${COOKIE_FILE} -X POST -d 'username=matheus&password=wrong' $HOST_URL/signin
echo ---

# sign in
curl -i -c ${COOKIE_FILE} -X POST -d 'username=matheus&password=root' $HOST_URL/signin
echo ---

# home
curl -i -b ${COOKIE_FILE} -X GET $HOST_URL/home
echo ---

# sign out
curl -i -b ${COOKIE_FILE} -X GET $HOST_URL/signout
echo ---

# home
curl -i -b ${COOKIE_FILE} -X GET $HOST_URL/home
